# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches : ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pm2 restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: "ubuntu"
          key: ${{ secrets.SSH_SSH_KEY }}
          script: |
            cd /home/opc/test-website-back
            git pull origin main
            npm install
            pm2 restart all
